# This is a basic workflow to help you get started with Actions

name: Sync collaboration Branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
            git config --global user.name "Abhyuditgaurav"
            git config --global user.email "gauravim05@gmail.com"

      - name: checkout collaboration branch
        run: |
          git fetch origin
          git checkout -b collaboration origin/collaboration || git checkout collaboration

      - name: Merge main into collaboration
        run: |
          git merge origin/main
          git push origin collaboration
          
